import Head from "next/head";
import {Flex, Heading, Center, Text, SimpleGrid} from "@chakra-ui/react";
import BusinessCard from "../components/BusinessCard"

export default function Home() {

  const IMAGE = 'https://images.unsplash.com/photo-1518051870910-a46e30d9db16?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80';
  



  return (
    <Flex direction="column" p="3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center as="header" mt="16">
        <Flex direction="column" align="center">
          <Heading color="purple.500" as="h1" size="3xl" mb="2">
            Villibiz
          </Heading>
          <Text fontSize="3xl">Villimalé Business Directory</Text>
        </Flex>
      </Center>

      <Center as="main" mt="16">
        <SimpleGrid columns={[1, 2, 2, 3]} spacing={10}>
        
        </SimpleGrid>
      </Center>
    </Flex>
  );
}
